Update laboratory1.sql
igortereshchenko/dbis pull request #45
Opened 2018-03-13 14:00 UTC by Cake1313

2018-03-28 14:20 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
SELECT VENDORS.vend_name, ORDERITEMS.item_price
FROM VENDORS, PRODUCTS, ORDERITEMS
WHERE 
    VENDORS.vend_id = PRODUCTS.vend_id and
    PRODUCTS.prod_id = ORDERITEMS.prod_id and
    ORDERITEMS.item_price IN (SELECT MIN(ORDERITEMS.item_price) FROM ORDERITEMS  );

2018-03-28 14:43 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
PROJECT UPPER(CUSTOMERS WHERE CUST_COUNTRY = 'USA' AND CUST_ZIP IS NOT NULL) (RENEME {CUST_NAME} client_name)

2018-03-28 15:02 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
PROJECT (( PROJECT (VENDORS) {VEND_NAME, VEND_ID} ) MINUS PROJECT( (VENDORS TIMES ORDERITEMS) TIMES (ORDERS TIMES PRODUCTS) ){VEND_NAME, VENDORS.VEND_ID} WHERE (ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM AND ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID AND PRODUCTS.VEND_ID = VENDORS.VEND_ID) ) {VEND_NAME};

2018-03-28 15:04 UTC, thors-trix requested changes
Request changes

2018-03-28 15:09 UTC, thors-trix requested changes

2018-03-28 15:09 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
>  -- LABORATORY WORK 1
Delete this
> -- LABORATORY WORK 1
 -- BY Servatmand_Mariam

2018-03-30 16:17 UTC, mars1317 reviewed
Checked

2018-03-30 16:38 UTC, thors-trix requested changes

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +TEMPORARY TABLESPACE TEMP
Use quotes " " on USERS and TEMP.
Use semicolon ; in the of cоmmand.
`DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +ALTER Servatmand QUOTA 100 MB ON USERS
Use full statement ALTER USER.
Use 100M instead of 100 MB.
Use semicolon ; in the of cоmmand.
`ALTER USER Servatmand QUOTA 100M ON USERS;`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +GRANT SELECT ANY TABLE TO USER
Use semicolon ; in the of command.
Use name of the user, instead of USER.
`GRANT "CONNECT" TO Servatmand; GRANT SELECT ANY TABLE TO Servatmand;`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
You must have three entities: Citizen, House_and_car, Citizen_house_car.
Each entity must have at least 4 columns/fields.

Entity Citizen must have fields: citizen_name VARCHAR(30), phone_number VARCHAR(13), person_id NUMBER(12), age NUMBER(3).
Entity House must have fields: street VARCHAR(15), floor_number NUMBER(3), resident_number NUMBER(4), building_year NUMBER(4).
Entity Car must have fields: car_id VARCHAR(20), car_model VARCHAR(15), car_type VARCHAR(15), release_year NUMBER(4).
Entitiy Citizen_house_car must have fields: person_id NUMBER(12), citizen_name VARCHAR(30), street VARCHAR(15), car_id VARCHAR(20).
Primary key for Citizen is 'person_id' and 'citizen_name', for House it's 'street', for Car it's 'car_id'.
Primary key for Citizen_house_car is 'person_id', 'citizen_name' and 'street'.
Foreign keys in the last table should be referenced by primary keys in entities Car, House and Citizen.

Regular expresions for each column in table:

Citizen table:
citizen_name - [A-Z][a-z]{2,14}\s[A-Z][a-z]{2,14}
Examples: Bob Marley, James Hetfield, Corey Taylor.
phone_number - +\d{11,14}
Examples: +14155552671, +13284734341, +19750736593
person_id - \d{10,12}
Examples: 936507643971, 605446309511, 985385736193, 785385630571.
age - [1-9]{1}\d{1,2}
Examples: 18, 74, 72.

House table:
street - [1-9]{1}[0-9]{1,2}\s[A-Z]{1}[a-z]{5,20}\s(St)
Examples: 43 Addams St, 2 Bennington St, 13 Richardson St.
floor_number - [1-9]{1}\d{1}
Examples: 1, 2, 45, 9, 15, 99.
resitent_number: [1-9]{1}\d{1,2}
Examples: 4, 14, 234, 632, 130, 35.
building_year - (19\d{2}|200\d{1}|201[0-8])
Examples: 1993, 2012, 1935.

Car table:
car_id - [A-Z]{2,3}-[0-9]{3}
Examples: GD-023, ANW-831, FE-933.
car_model: [A-Z]{1}[a-z]{5,12}
Examples: Nissan, Toyota, Renault.
car_type: [A-Z]{1}[a-z]{5,12}
Examples: Sports, Mini, Minivan, Regular.
release_year: (19\d{2}|200\d{1}|201[0-8])
Examples: 1943, 1966, 1989, 2012, 2004.

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +GRANT INSERT TO Servatmand
Use proper statement INSERT ANY TABLE.
Use semicolon ; in the end of command.
`GRANT INSERT ANY TABLE TO Servatmand;`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
`SELECT VENDORS.vend_name, ORDERITEMS.item_price
FROM VENDORS, PRODUCTS, ORDERITEMS
WHERE
VENDORS.vend_id = PRODUCTS.vend_id and
PRODUCTS.prod_id = ORDERITEMS.prod_id and
ORDERITEMS.item_price IN (SELECT MIN(ORDERITEMS.item_price) FROM ORDERITEMS );`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
`RENAME(
PROJECT
UPPER(CUSTOMERS
WHERE CUST_COUNTRY = 'USA'
AND CUST_ZIP IS NOT NULL)
{CUST_NAME}
) CUST_NAME -> client_name`

2018-03-30 16:38 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
`PROJECT LOWER(( PROJECT (VENDORS) {VEND_NAME, VEND_ID}) MINUS PROJECT ((VENDORS TIMES ORDERITEMS) TIMES (ORDERS TIMES PRODUCTS) ){VEND_NAME, VENDORS.VEND_ID} WHERE (ORDERITEMS.ORDER_NUM = ORDERS.ORDER_NUM AND ORDERITEMS.PROD_ID = PRODUCTS.PROD_ID AND PRODUCTS.VEND_ID = VENDORS.VEND_ID)) (RENAME {VEND_NAME} vendor_name);`

2018-03-30 17:33 UTC, mars1317 reviewed
Fixed

2018-03-30 17:44 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +CREATE table Citizen(
Нужно добавить запятые после каждого нового поля, последнее поле без точки и без зяпятой, пример:

`CREATE table Citizen(
citizen_name VARCHAR(30),
phone_number VARCHAR(13),
person_id NUMBER(12)
);`

2018-03-30 17:46 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
После каждой команды alter table поставь точку с запятой, пример:
`ALTER TABLE House
    add CONSTRAINT house_pk primary key (street);`

2018-03-30 17:47 UTC, LocoInverso commented on km61/Servatmand_Mariam/laboratory1.sql
> +
Это нужно удалить, не имеет смысла:
`ALTER TABLE person_auto
    add CONSTRAINT number_pk primary key (number_auto);
ALTER TABLE person_house_auto
    add CONSTRAINT person_house_auto_pk primary key (adress_fk, number_auto_fk);`

2018-03-30 17:48 UTC, thors-trix reviewed
Исправляй

2018-03-30 18:12 UTC, thors-trix approved these changes
Найс

2018-04-17 06:37 UTC, closed without merging