julia
igortereshchenko/dbis pull request #53
Opened 2018-03-15 11:25 UTC by JuliaKovalchook

2018-03-30 20:12 UTC, Alexandr-gw requested changes

2018-03-30 20:12 UTC, Alexandr-gw commented on km62/Kovalchuk_Yuliia/laboratory1.sql
> +---------------------------------------------------------------------------*/
There should be tables - 'Human' and 'Phone' with many to many connection, because one person can own two different marks of phone and phone's which made by one company can be bought by many different people's. So table 'Human' and 'Phone' should have reference to each other's. And we also need the auxiliary table 'Orders' which will contain info about orders.
# Human
1) person_id - number(20) primary key not null,
2) first_name - varchar2(30) not null
Regexp - ^[A-Z][a-z]{1,29}$
3) second_name - varchar2(30) not null
Regexp - ^[A-Z][a-z]{1,29}$
4) country - varchar2(100) not null
Regexp - ^([A-Z][a-z]+)+$
# Phone
1) phone_imei -number(15) primary key not null,
2) owner_id - number(20) not null,
3) phone_model - varchar2(20) not null,
Regexp - ^[A-Z][a-z]{19}$ 
4) phone_mark - varchar2(15) not null,
Regexp - ^[A-Z][a-z]{14}$ 
# Orders
1) owner_id - number(20) primary key not null,
2) order_num -number(15) not null,
3) order_date - number(10) not null,
4) phone_imei -number(15) primary key not null,

2018-03-30 20:12 UTC, Alexandr-gw commented on km62/Kovalchuk_Yuliia/laboratory1.sql
> +---------------------------------------------------------------------------*/
SQL request:

SELECT prod_price
FROM products, orderitems
MINUS
SELECT prod_price 
FROM products, orderitems
WHERE orderitems.prod_id = Products.prod_id ;

2018-03-30 20:12 UTC, Alexandr-gw commented on km62/Kovalchuk_Yuliia/laboratory1.sql
> +---------------------------------------------------------------------------*/
Request in algebra Kodda:

PROJECT Customers WHERE cust_id in(PROJECT orders WHERE order_num in (POJECT orderitems WHERE item_price in(PROJECT orderitems{max(item_price)}){order_num}){cust_id})
{Customers RENAME cust_name AS Customer_name}

2018-03-30 20:12 UTC, Alexandr-gw commented on km62/Kovalchuk_Yuliia/laboratory1.sql
> +SELECT USERS_NAME,
Here should be name of customer where CUST.cust_id  same in PROD.cust_id and max(PROD.prod_price)

2018-05-21 16:42 UTC, JuliaKovalchook commented
rr

2018-06-07 20:50 UTC, JuliaKovalchook commented
https://plot.ly/dashboard/JuliaKovalchuk:6/view#/

2018-06-07 20:50 UTC, closed without merging

2018-06-07 20:51 UTC, JuliaKovalchook commented
https://plot.ly/dashboard/JuliaKovalchuk:6/view#/

2018-06-07 20:54 UTC, JuliaKovalchook commented
https://plot.ly/dashboard/JuliaKovalchuk:6/view#/

2018-06-07 21:32 UTC, JuliaKovalchook commented
![erd](https://user-images.githubusercontent.com/22946872/41127375-64a7fdc0-6ab3-11e8-95ad-b90ccc035df6.png)