new code
igortereshchenko/dbis pull request #91
Opened 2018-03-24 15:06 UTC by dbisstudent

2018-03-24 15:14 UTC, igortereshchenko commented
@teacherdbis

2018-03-25 17:49 UTC, teacherdbis requested changes

2018-03-25 17:49 UTC, teacherdbis commented on test/Tereshchenko_Igor/laboratory1.sql
> --- BY Tereshchenko_Igor
Delete comments

2018-03-25 17:49 UTC, teacherdbis commented on test/Tereshchenko_Igor/laboratory1.sql
> +        SELECT DISTINCT             -- select all combination of customer and product
Delete DISTINCT

2018-03-25 17:50 UTC, closed without merging